services:
  test-mariadb:
    image: mariadb:11.4-noble
    environment:
      MARIADB_ROOT_PASSWORD: testpass
      MARIADB_DATABASE: testdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
